# Generated by Django 4.2.9 on 2026-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_verified_remove_user_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
