# Generated by Django 4.2.9 on 2026-04-10 17:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_message', models.CharField(db_index=True, max_length=500)),
                ('url_path', models.CharField(db_index=True, max_length=200)),
                ('error_type', models.CharField(default='500', max_length=10)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Application Error',
                'verbose_name_plural': 'Application Errors',
                'db_table': 'app_errors',
                'ordering': ['-last_seen_at'],
                'unique_together': {('error_message', 'url_path')},
            },
        ),
    ]
