# Generated by Django 4.2.9 on 2026-04-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apperror',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
