# Generated by Django 4.2.9 on 2026-04-10 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('view', 'View'), ('map_open', 'Map Opened'), ('time_spent', 'Time Spent')], db_index=True, max_length=15)),
                ('value', models.PositiveIntegerField(default=1, help_text='Seconds for time_spent, 1 for counts')),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
