# Generated by Django 4.2.9 on 2026-04-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='hosts.listing'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['listing', 'event_type'], name='analytics_e_listing_37fafe_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['listing', 'ip_hash'], name='analytics_e_listing_4b3314_idx'),
        ),
    ]
