# Generated by Django 4.2.9 on 2026-05-15 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0007_listing_is_active_on_map_listing_last_started_at_and_more'),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUniqueVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ip_hash', models.CharField(max_length=64)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.listing')),
            ],
            options={
                'db_table': 'daily_unique_visitors',
            },
        ),
        migrations.CreateModel(
            name='ListingDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('map_opens_count', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.PositiveIntegerField(default=0)),
                ('unique_visitors_count', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='hosts.listing')),
            ],
            options={
                'verbose_name': 'Daily Listing Stat',
                'verbose_name_plural': 'Daily Listing Stats',
                'db_table': 'listing_daily_stats',
                'unique_together': {('listing', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='AnalyticsEvent',
        ),
        migrations.AddIndex(
            model_name='dailyuniquevisitor',
            index=models.Index(fields=['listing', 'date', 'ip_hash'], name='daily_uniqu_listing_845f61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyuniquevisitor',
            unique_together={('listing', 'date', 'ip_hash')},
        ),
    ]
