# Generated by Django 4.2.9 on 2026-04-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['category', 'service_name'], 'verbose_name': 'Service Item'},
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
