# Generated by Django 4.2.9 on 2026-04-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_alter_serviceitem_options_serviceitem_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='operating_hours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
