# Generated by Django 4.2.9 on 2026-05-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_listing_operating_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
