# Generated by Django 4.2.9 on 2026-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_category_alter_listing_status_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_active_on_map',
            field=models.BooleanField(default=True, help_text='Toggle to show/hide on public map'),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
