# Generated by Django 4.2.9 on 2026-05-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0007_listing_is_active_on_map_listing_last_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_covers/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location_name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
