# Generated by Django 4.2.9 on 2026-05-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0008_listing_cover_image_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_svg',
        ),
    ]
